name: Android Internal Github (Killer)

on:
  push:
    branches:
      - master
    paths:
      - 'apps/killer/**'
      - '!packages/**'

jobs:
  skip-if-packages-changed:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.check.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check if packages/** changed
        id: check
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^packages/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  real-job:
    needs: skip-if-packages-changed
    if: needs.skip-if-packages-changed.outputs.should_skip == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Continue with real job
        run: echo "Packages not changed. Running job..."
